### ISSUE TITLE
[IDEA] add some basic numerical methods

### ISSUE THREAD

**Issue by kookma** [rweed/ModForUtils#1]
good to add some basic numerical methods like: interpolation, quadrature, IVP and BVP solver.

**Comment by rweed** [comment]
@kookma, thanks for the suggestions. This repository is currently a "work in progress" and is intended to contain code I've already written and serve as a convenient staging area for sharing the code with people that might want to include it in other projects such as the Fortran stdlib project.

An interpolation package is planned that will include stable Lagrange (barycentric) interpolator, tabular interpolation (Neville's method) along with some Bezier and natural and parametric spline interpolators. I also have some utilities I can add that compute Gauss points and weights etc for quadrature. However, QUADPACK is probably your best bet for many (most) quadrature problems. I have the beginnings of a full Modern Fortran NURBS/B-spline package but that wil take much more work before its ready for general use.

Other than some problem specific Runga-Kutta schemes I don't have anything already written for IVP and BVP problems
